{
  "hash": "5848b050fc7917061c58d1880bfc2831",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Mini-Project-3\"\ndate: \"03-05-25\"\nauthor: \"Clayton Fogler\"\n---\n\n\n\n\n# Mini Project 3: Simulation to Invesitgate Confidence Intervals\n\n#### Statement of Integrity\n\n“I have followed all rules for collaboration for this project, and I have not used generative AI on this project.”\n\n#### packages for this project\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(purrr)\n```\n:::\n\n\n\n\n## Step 1:\n\nn = 5, n = 20, n = 50\n\np = 0.46, p = 0.75\n\n-   Note: These 3 different sample sizes and 2 different population proportions meets the requirments in which at least two of the six settings violate the large sample assumption for the asymptotic confidence interval while two of the six settings hold the assumption.\n\n## Step 2: Starting with one of the setting that holds the large sample assumption, construct at least 5,000 sample proportions and 5000 associated confidence intervals\n\n#### n = 50, p = 0.46\n\n1)  This assumption holds since np \\> 10 and n(1-p) \\> 10\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n50*0.46\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23\n```\n\n\n:::\n\n```{.r .cell-code}\n50*(1-0.46)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27\n```\n\n\n:::\n:::\n\n\n\n\n2)  Constructing 5,000 sample proportions and 5000 associated C.I.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenerate_onesamp_cis <- function(n, p, alpha) {\n  \n  ## generate a single sample (one of nsim data sets)\n  x <- rbinom(1, n, p)\n  \n  ## compute the bounds of the C.I.\n  point_est <- x/n\n  lb <- point_est - qnorm(1 - alpha / 2) * sqrt(point_est * (1 - point_est)/ n)\n  ub <- point_est + qnorm(1 - alpha / 2) * sqrt(point_est * (1 - point_est)/ n)\n  \n  ## put everything into a tibble\n  out_df <- tibble(point_est, lb, ub)\n  \n  return(out_df)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## define parameters to use in our function\nn <- 50 # sample size\np <- 0.46\nalpha <- 0.1 # used to construct 1 -alpha CI (how much should be in the tails)\n\n## generate 5000 sample proportions and 5000 associated C.I.\nnsim <- 5000 # the number of simulations\n\nmany_ci_df <- map(1:nsim,\n                  \\(i) generate_onesamp_cis(n = n, p = p, alpha = alpha)) |>\n  bind_rows()\nmany_ci_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 3\n   point_est    lb    ub\n       <dbl> <dbl> <dbl>\n 1      0.48 0.364 0.596\n 2      0.5  0.384 0.616\n 3      0.56 0.445 0.675\n 4      0.3  0.193 0.407\n 5      0.44 0.325 0.555\n 6      0.4  0.286 0.514\n 7      0.6  0.486 0.714\n 8      0.54 0.424 0.656\n 9      0.44 0.325 0.555\n10      0.42 0.305 0.535\n# ℹ 4,990 more rows\n```\n\n\n:::\n:::\n\n\n\n\n## Step 3: From the 5000 confidence intervals, calculate both 1) the average interval width and 2) the coverage rate.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## this code will calculate both 1) interval width and 2) the coverage rate for all 5000 simulations\n\nmany_ci_df <- many_ci_df |> mutate(ci_width = ub - lb,\n                                    ci_cover_ind = if_else(p > lb & p < ub,\n                                                           true = 1,\n                                                           false = 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## this code will calculate both 1) average interval width and 2) average coverage rate for the 5000 simulations\n\nmany_ci_df |> summarise(avg_width = mean(ci_width),\n                        coverage_rate = mean(ci_cover_ind))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_width coverage_rate\n      <dbl>         <dbl>\n1     0.230         0.885\n```\n\n\n:::\n:::\n\n\n\n\n## Step 4: Repeat steps 2 and 3 for the 5 other settings, recording the average interval width and the coverage rate for each of these other 5 settings.\n\n#### n = 50, p = 0.75\n\nThis assumption holds since np \\> 10 and n(1-p) \\> 10\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n50*0.75\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 37.5\n```\n\n\n:::\n\n```{.r .cell-code}\n50*(1-0.75)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12.5\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## define parameters to use in our function\nn <- 50 # sample size\np <- 0.75\nalpha <- 0.1 # used to construct 1 -alpha CI (how much should be in the tails)\n\n## generate 5000 sample proportions and 5000 associated C.I.\nnsim <- 5000 # the number of simulations\n\nmany_ci_df <- map(1:nsim,\n                  \\(i) generate_onesamp_cis(n = n, p = p, alpha = alpha)) |>\n  bind_rows()\nmany_ci_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 3\n   point_est    lb    ub\n       <dbl> <dbl> <dbl>\n 1      0.72 0.616 0.824\n 2      0.74 0.638 0.842\n 3      0.72 0.616 0.824\n 4      0.76 0.661 0.859\n 5      0.7  0.593 0.807\n 6      0.76 0.661 0.859\n 7      0.68 0.571 0.789\n 8      0.76 0.661 0.859\n 9      0.8  0.707 0.893\n10      0.76 0.661 0.859\n# ℹ 4,990 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## this code will calculate both 1) interval width and 2) the coverage rate for all 5000 simulations\n\nmany_ci_df <- many_ci_df |> mutate(ci_width = ub - lb,\n                                    ci_cover_ind = if_else(p > lb & p < ub,\n                                                           true = 1,\n                                                           false = 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## this code will calculate both 1) average interval width and 2) average coverage rate for the 5000 simulations\n\nmany_ci_df |> summarise(avg_width = mean(ci_width),\n                        coverage_rate = mean(ci_cover_ind))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_width coverage_rate\n      <dbl>         <dbl>\n1     0.199         0.878\n```\n\n\n:::\n:::\n\n\n\n\n------------------------------------------------------------------------\n\n#### n = 5, p = 0.46\n\nThis assumption does not hold since np \\> 10 and n(1-p) \\> 10 are both not true\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n5*0.46\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.3\n```\n\n\n:::\n\n```{.r .cell-code}\n5*(1-0.46)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.7\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## define parameters to use in our function\nn <- 5 # sample size\np <- 0.46\nalpha <- 0.1 # used to construct 1 -alpha CI (how much should be in the tails)\n\n## generate 5000 sample proportions and 5000 associated C.I.\nnsim <- 5000 # the number of simulations\n\nmany_ci_df <- map(1:nsim,\n                  \\(i) generate_onesamp_cis(n = n, p = p, alpha = alpha)) |>\n  bind_rows()\nmany_ci_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 3\n   point_est      lb    ub\n       <dbl>   <dbl> <dbl>\n 1       0.4  0.0396 0.760\n 2       0.4  0.0396 0.760\n 3       0.6  0.240  0.960\n 4       0.2 -0.0942 0.494\n 5       0.2 -0.0942 0.494\n 6       0.4  0.0396 0.760\n 7       0.2 -0.0942 0.494\n 8       0.4  0.0396 0.760\n 9       0.8  0.506  1.09 \n10       0.6  0.240  0.960\n# ℹ 4,990 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## this code will calculate both 1) interval width and 2) the coverage rate for all 5000 simulations\n\nmany_ci_df <- many_ci_df |> mutate(ci_width = ub - lb,\n                                    ci_cover_ind = if_else(p > lb & p < ub,\n                                                           true = 1,\n                                                           false = 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## this code will calculate both 1) average interval width and 2) average coverage rate for the 5000 simulations\n\nmany_ci_df |> summarise(avg_width = mean(ci_width),\n                        coverage_rate = mean(ci_cover_ind))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_width coverage_rate\n      <dbl>         <dbl>\n1     0.630         0.807\n```\n\n\n:::\n:::\n\n\n\n\n------------------------------------------------------------------------\n\n#### n = 5, p = 0.75\n\nThis assumption does not hold since np \\> 10 and n(1-p) \\> 10 are both not true\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n5*0.75\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.75\n```\n\n\n:::\n\n```{.r .cell-code}\n5*(1-0.75)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.25\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## define parameters to use in our function\nn <- 5 # sample size\np <- 0.75\nalpha <- 0.1 # used to construct 1 -alpha CI (how much should be in the tails)\n\n## generate 5000 sample proportions and 5000 associated C.I.\nnsim <- 5000 # the number of simulations\n\nmany_ci_df <- map(1:nsim,\n                  \\(i) generate_onesamp_cis(n = n, p = p, alpha = alpha)) |>\n  bind_rows()\nmany_ci_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 3\n   point_est     lb    ub\n       <dbl>  <dbl> <dbl>\n 1       1   1      1    \n 2       0.8 0.506  1.09 \n 3       0.8 0.506  1.09 \n 4       0.6 0.240  0.960\n 5       0.8 0.506  1.09 \n 6       0.8 0.506  1.09 \n 7       1   1      1    \n 8       0.8 0.506  1.09 \n 9       0.8 0.506  1.09 \n10       0.4 0.0396 0.760\n# ℹ 4,990 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## this code will calculate both 1) interval width and 2) the coverage rate for all 5000 simulations\n\nmany_ci_df <- many_ci_df |> mutate(ci_width = ub - lb,\n                                    ci_cover_ind = if_else(p > lb & p < ub,\n                                                           true = 1,\n                                                           false = 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## this code will calculate both 1) average interval width and 2) average coverage rate for the 5000 simulations\n\nmany_ci_df |> summarise(avg_width = mean(ci_width),\n                        coverage_rate = mean(ci_cover_ind))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_width coverage_rate\n      <dbl>         <dbl>\n1     0.494         0.746\n```\n\n\n:::\n:::\n\n\n\n\n------------------------------------------------------------------------\n\n#### n = 20, p = 0.46\n\nThis assumption does not hold since np \\> 10 and n(1-p) \\> 10 are not both true\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n20*0.46\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.2\n```\n\n\n:::\n\n```{.r .cell-code}\n20*(1-0.46)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.8\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## define parameters to use in our function\nn <- 20 # sample size\np <- 0.46\nalpha <- 0.1 # used to construct 1 -alpha CI (how much should be in the tails)\n\n## generate 5000 sample proportions and 5000 associated C.I.\nnsim <- 5000 # the number of simulations\n\nmany_ci_df <- map(1:nsim,\n                  \\(i) generate_onesamp_cis(n = n, p = p, alpha = alpha)) |>\n  bind_rows()\nmany_ci_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 3\n   point_est    lb    ub\n       <dbl> <dbl> <dbl>\n 1      0.5  0.316 0.684\n 2      0.55 0.367 0.733\n 3      0.35 0.175 0.525\n 4      0.65 0.475 0.825\n 5      0.35 0.175 0.525\n 6      0.55 0.367 0.733\n 7      0.6  0.420 0.780\n 8      0.45 0.267 0.633\n 9      0.5  0.316 0.684\n10      0.35 0.175 0.525\n# ℹ 4,990 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## this code will calculate both 1) interval width and 2) the coverage rate for all 5000 simulations\n\nmany_ci_df <- many_ci_df |> mutate(ci_width = ub - lb,\n                                    ci_cover_ind = if_else(p > lb & p < ub,\n                                                           true = 1,\n                                                           false = 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## this code will calculate both 1) average interval width and 2) average coverage rate for the 5000 simulations\n\nmany_ci_df |> summarise(avg_width = mean(ci_width),\n                        coverage_rate = mean(ci_cover_ind))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_width coverage_rate\n      <dbl>         <dbl>\n1     0.357          0.88\n```\n\n\n:::\n:::\n\n\n\n\n------------------------------------------------------------------------\n\n#### n = 20, p = 0.75\n\nThis assumption does not hold since np \\> 10 and n(1-p) \\> 10 are not both true.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n20*0.75\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15\n```\n\n\n:::\n\n```{.r .cell-code}\n20*(1-0.75)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## define parameters to use in our function\nn <- 20 # sample size\np <- 0.75\nalpha <- 0.1 # used to construct 1 -alpha CI (how much should be in the tails)\n\n## generate 5000 sample proportions and 5000 associated C.I.\nnsim <- 5000 # the number of simulations\n\nmany_ci_df <- map(1:nsim,\n                  \\(i) generate_onesamp_cis(n = n, p = p, alpha = alpha)) |>\n  bind_rows()\nmany_ci_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 3\n   point_est    lb    ub\n       <dbl> <dbl> <dbl>\n 1      0.8  0.653 0.947\n 2      0.8  0.653 0.947\n 3      0.8  0.653 0.947\n 4      0.8  0.653 0.947\n 5      0.85 0.719 0.981\n 6      0.65 0.475 0.825\n 7      0.7  0.531 0.869\n 8      0.8  0.653 0.947\n 9      0.55 0.367 0.733\n10      0.7  0.531 0.869\n# ℹ 4,990 more rows\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## this code will calculate both 1) interval width and 2) the coverage rate for all 5000 simulations\n\nmany_ci_df <- many_ci_df |> mutate(ci_width = ub - lb,\n                                    ci_cover_ind = if_else(p > lb & p < ub,\n                                                           true = 1,\n                                                           false = 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## this code will calculate both 1) average interval width and 2) average coverage rate for the 5000 simulations\n\nmany_ci_df |> summarise(avg_width = mean(ci_width),\n                        coverage_rate = mean(ci_cover_ind))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_width coverage_rate\n      <dbl>         <dbl>\n1     0.308         0.876\n```\n\n\n:::\n:::\n\n\n\n\n------------------------------------------------------------------------\n\n## Table with all of our calculations:\n\n|            |               | n = 5  | n = 20 | n = 50 |\n|:----------:|:-------------:|:------:|:------:|:------:|\n| $p = 0.46$ | Coverage Rate | 0.8048 | 0.8812 | 0.8812 |\n| $p = 0.75$ | Coverage Rate | 0.7474 | 0.8626 | 0.8774 |\n|            |               |        |        |        |\n| $p = 0.46$ | Average Width | 0.6275 | 0.3571 | 0.2295 |\n| $p = 0.75$ | Average Width | 0.4950 | 0.3065 | 0.1987 |\n\n: Table of Results {.striped .hover}\n\n------------------------------------------------------------------------\n\n## Summary of our Findings\n\nOur findings can be broken into three different sample size: n = 5, n = 20, and n = 50.\n\nFirst, n = 5. Whether p = 0.46 or p = 0.75, they both did not hold the \"large sample assumption\". After the 5000 simulations, when p = 0.46, we got an average width of 0.6275 and coverage rate of 0.8048. We are not surprised that the average width is big because our n is so small. Our converge rate is roughly about 0.80, which is not what we wanted since we are doing a 90% C.I.This can be explained because with such a small n, our phats are ending up outside our confidence interval. When p = 0.75, we got an average width of 0.4950 and a coverage rate of 0.7474. Again, we are not surprised by the big interval and smaller than expected coverage rate due to the fact we have a small n and did not hold the \"large sample assumption\".\n\nWhen n = 20, we still saw that it didn't matter what our p was. Whether it was 0.46 or 0.75, the \"large sample assumption\" still does not hold. After the 5000 simulations, when p = 0.46, the average width was 0.3571 and coverage rate of 0.8812. We notice that our average width of the confidence interval has decreased from n = 5, which makes sense as a larger sample size should give us a smaller confidence interval. We also notice that our coverage rate was closer to the 0.9 we are looking for. This coverage rate was much closer due to the fact that one of the two test did pass, with one of the test being very close to passing. When p = 0.75, we get an average width of 0.3065 and a coverage rate of 0.8626. Again, like the p = 0.46, we noticed improved numbers as our confidence interval was smaller and our coverage rate was much closer to 0.9 then when n = 5.\n\nFinally, when n = 50, we saw that when our p = 0.46 or p = 0.75, the \"large sample assumption\" passed. When p = 0.46, we got an average width of 0.2295 and a coverage rate of 0.8812. We notice again as we increased n, we obtain an even smaller average width and a coverage rate of almost 0.90 This is great as this is what we expect when trying to take a 90% C.I. We get very similar results when p = 0.75 as average width was 0.1987 (the smallest out of all 6 examples) and a coverage rate of 0.8774. This was the smallest average width, which was not suprising as n = 50. This was also again a very close coverage rate to 0.90 as both \"large sample assumptions passed\".\n\nOverall, the biggest take away from our simulations is we get the smallest average width of an interval and best coverage rate when we have a large n and pass the \"large sample assumption\".",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}